name: Publish to npm

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make stable release to npm
        uses: epeli/npm-release@v1
        with:
          type: stable
          token: ${{ secrets.NPM_TOKEN }}
